### ISSUE TITLE
About

### ISSUE THREAD

**Issue by Natalia-Katie** [Ved-programmer/Login-System#23]
Hi, What is this repository all about, I mean what are it's uses ? Please tell me.

**Comment by Ved-programmer** [comment]
This is a login system, made with python. This repository is a random project that I have made. There is no purpose for this project, I mean someone could use this project by integrating this code with the app they are building for authentication. However the main reason I made this is because I felt like it, nothing much. I like building fun little stupid projects, so I made this. No use but fun to play with. You can ignore it or mess around with it.

**Comment by Ved-programmer** [comment]
If you don't have any other questions then please close this issue.

**Comment by Natalia-Katie** [comment]
Yeah I don't have any other question, thanks for telling, by the way I'm new to GitHub, can you tell me about GitHub, I mean not here, if you're ok I will give my email address to you : )

**Comment by Ved-programmer** [comment]
Ya sure, I am open to meeting new people like navdeep, you etc. Send me your email on this issue. I will send an email to you back to confirm.

**Comment by Natalia-Katie** [comment]
its nataliaKatie2008@gmail.com, please try sending an email to. Well asked out of curiosity, please don't take it personally, where are you from?

**Comment by Ved-programmer** [comment]
I'm from India

**Comment by Ved-programmer** [comment]
sent a mail right now, check it
